const RightData = [
    {   
        id : 21,
        planTitle : ' Starter plan',
        planPiceF : '19',
        planPicePaisa : '.99',
        planCurrency : '$',
        planOffer : 'Save 40%',
        planIcon : <i className="feather icon-check"></i>,
        planList1 : 'Commercial License',
        planList2 : '00+ HTML UI Elements',
        planList3 : 'Unlimited Domain Support',
        planList4 : '6 months premium support',
        planList5 : 'Lifetime updates',    
     },
     {  
         id : 22,
         planTitle : ' Starter plan',
        planPiceF : '20',
        planPicePaisa : '.99',
        planCurrency : '$',
        planOffer : 'Save 40%',
        planIcon : <i className="feather icon-check"></i>,
        planList1 : 'Commercial License',
        planList2 : '00+ HTML UI Elements',
        planList3 : 'Unlimited Domain Support',
        planList4 : '6 months premium support',
        planList5 : 'Lifetime updates',
         
     },
     {  
         id : 23,
         planTitle : ' Starter plan',
         planPiceF : '21',
         planPicePaisa : '.99',
         planCurrency : '$',
         planOffer : 'Save 40%',
         planIcon : <i className="feather icon-check"></i>,
         planList1 : 'Commercial License',
         planList2 : '00+ HTML UI Elements',
         planList3 : 'Unlimited Domain Support',
         planList4 : '6 months premium support',
         planList5 : 'Lifetime updates',
     },
     {  
         id : 24,
         planTitle : ' Starter plan',
         planPiceF : '22',
         planPicePaisa : '.99',
         planCurrency : '$',
         planOffer : 'Save 40%',
         planIcon : <i className="feather icon-check"></i>,
         planList1 : 'Commercial License',
         planList2 : '00+ HTML UI Elements',
         planList3 : 'Unlimited Domain Support',
         planList4 : '6 months premium support',
         planList5 : 'Lifetime updates',
     },
]

export default RightData;